name: Compile JOSS Paper
on:
  push:
    paths:
      - 'paper.md'
      - 'paper.bib'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build paper
        uses: openjournals/openjournals-postit@v1
        with:
          paper_path: paper.md
          journal: joss
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
